name: Update Tokens

on:
  repository_dispatch:
    types:
      - update-tokens

jobs:
  update-tokens-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create/Update tokens file
        run: |
          echo "${{ github.event.client_payload.tokens }}" > tokens.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tokens.json
          git commit -m "${{ github.event.client_payload.commitMessage }}"
          git push

      # 필요에 따라 추가 작업을 정의할 수 있습니다.
