name: Update Tokens

on:
  repository_dispatch:
    types:
      - update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.tokens }}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ${{ github.event.client_payload.filename }}
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "${{ github.event.client_payload.commitMessage }}"
            git push origin main
          fi
      