name: Transform tokens sent from Figma

on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create "tokens" directory
        run: mkdir -p tokens

      - name: Create JSON from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }}
          json: ${{ github.event.client_payload.tokens }}
          dir: 'tokens'

      # Configure Git identity (이 부분이 필요합니다)
      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Create Pull Request 
      - name: Create PR 
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ github.event.client_payload.commitMessage || 'Tokens updated' }}
          title: "Design tokens updated"
          body: "Design tokens have been updated via Figma and need to be reviewed."
          branch: "create-pull-request/patch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
