name: Update Tokens

on:
  repository_dispatch:
    types: [update-tokens]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Build Design Tokens
        run: npm run build

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Update design tokens"
          git push origin main