name: Update Tokens

on:
  repository_dispatch:
    types:
      - update-tokens

jobs:
  update-tokens-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.tokens }}" > tokens.json

      - name: test
        run: echo "${{ github.repository }}"

      - name: Commit and push changes
        run:
          git add tokens.json
          git commit -m "${{ github.event.client_payload.commitMessage }}"
          git push https://github.com/${{ github.repository }}.git HEAD:main

      
