name: Update Tokens

on:
  repository_dispatch:
    types:
      - update-tokens

jobs:
  update-tokens-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.tokens }}" > tokens.json
      
      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.filename }}"
        
      - name: test
        run: echo "${{ github.repository }}"

      - name: email
        run: git config --global user.email "g_e@daum.com"

      - name: name
        run: git config --global user.name "ge_design_token"

      - name: add
        run: git add tokens.json

      - name: commit
        run: git commit -m "${{ github.event.client_payload.commitMessage }}"
      
      - name: push
        run: git push https://github.com/${{ github.repository }}.git HEAD:main

      
