name: Update Tokens

on:
  repository_dispatch:
    types:
      - update-tokens

jobs:
  update-tokens-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.tokens }}" > tokens.json
