name: Update Tokens

on:
  repository_dispatch:
    types:
      - update-tokens

jobs:
  update-tokens-job:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v2

      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.tokens }}" > tokens.json
      
      - name: Create/Update tokens file
        run: echo "${{ github.event.client_payload.filename }}"
        
      - name: test
        run: echo "${{ github.repository }}"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tokens.json
          git commit -m "${{ github.event.client_payload.commitMessage }}"
          git push https://$GH_PAT@github.com/${{ github.repository }}.git HEAD:main
